### ISSUE TITLE
Files Missing

### ISSUE THREAD

**Issue by cloudjanak** [sourabh-shri/SSXmpp#1]
Thanks for this great work but some files are still missing can you pleas add that files ?

Thanking you.

**Comment by sourabh-shri** [comment]
Sure I'll update it asap

**Comment by cloudjanak** [comment]
I'm eagerly waiting for this development can you mail me this project,i tried to implement Group chat but failed.I stucked here.

**Comment by sourabh-shri** [comment]
What the error you got or how you try to implement this ?

**Comment by cloudjanak** [comment]
Some files are missing

**Comment by sourabh-shri** [comment]
Please try now

**Comment by cloudjanak** [comment]
Hearty i appreciate your help.
Thank you.

**Comment by sourabh-shri** [comment]
in SSXmppConstant.h you have to add your xmpp server IP and port and you have to do change your server domain ,right now it is @canopus-pc

**Comment by cloudjanak** [comment]
No password option.

**Comment by sourabh-shri** [comment]
For now password will same for all the users ,you can see it in
SSXmppConstant.h  UserPassword
