### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by cloudjanak** [sourabh-shri/SSXmpp#2]
2016-02-25 16:46:44.438 SSXmpp[21038:417157] Error Domain=XMPPStreamErrorDomain Code=1 "Attempting to connect while already connected or connecting." UserInfo={NSLocalizedDescription=Attempting to connect while already connected or connecting.}

**Comment by cloudjanak** [comment]
can you set my jid and password for testing domain zetrixweb.p1.im user 9408540266 pass 123456

**Comment by sourabh-shri** [comment]
Have you set HostName,HostPort and Userpostfix in SSXmppConstant ?

**Comment by cloudjanak** [comment]
2016-02-25 16:46:44.438 SSXmpp[21038:417157] Error Domain=XMPPStreamErrorDomain Code=1 "Attempting to connect while already connected or connecting." UserInfo={NSLocalizedDescription=Attempting to connect while already connected or connecting.}

yes,i am getting above message on login click.

**Comment by sourabh-shri** [comment]
Send me the SSXmppConstant which is you are using .

**Comment by cloudjanak** [comment]
9408540266,8128120777,9724758585,6464652873,9998354654

server zetrixweb.p1.im

**Comment by cloudjanak** [comment]
Any update?

**Comment by sourabh-shri** [comment]
Hi 

Surely I'll give you updates tomorrow

**Comment by cloudjanak** [comment]
Thanks a lot sir.

**Comment by sourabh-shri** [comment]
@JanakLN 
It's your xmpp server error.
Please check HostName ( IP of your server )  and HostPort (port number) and please check domain name of your xmpp server in  SSXmppConstant.h

**Comment by cloudjanak** [comment]
can you add my xmpp domain its zetrixweb.p1.im and default 522 port of xmpp.

**Comment by cloudjanak** [comment]
and its working with other demo project of one - to - one chat.

**Comment by sourabh-shri** [comment]
#define HostName @"your Ip"
#define HostPort 5222

#define Userpostfix                         @"ssxmpp@zetrixweb.p1.im"
#define Grouppostfix                        @"@ssxmpp.zetrixweb.p1.im"

Update this in your code

**Comment by cloudjanak** [comment]
Same issue

**Comment by sourabh-shri** [comment]
@JanakLN 

you can take update now

**Comment by cloudjanak** [comment]
Still not able to login.
But i appreciate you help from bottom of my heart .

**Comment by sourabh-shri** [comment]
can you give me your ip address in my mail ID sourabh.shrivastava20@gmail.com so that i can find out whats the problem is it ?
